<?php

namespace AppBundle\Repository;

/**
 * CartProductBackOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartProductBackOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
