<?php

namespace AppBundle\Repository;

/**
 * CartProductLineNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartProductLineNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
