<?php

namespace AppBundle\Repository;

/**
 * OfficeLineNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeLineNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
