<?php

namespace AppBundle\Repository;

/**
 * PartNumberPrefixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartNumberPrefixRepository extends \Doctrine\ORM\EntityRepository
{
}
