<?php

namespace AppBundle\Repository;

/**
 * ShippingMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
