<?php

namespace AppBundle\Repository;

/**
 * StockLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
