app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
_user_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/group
#api:
              #    type:     rest
              #    resource: