# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     authentication.handler.login_success_handler:
         class:  AppBundle\Security\LoginSuccessHandler
         arguments:  ['@router', '@security.authorization_checker']

     app.form.registration:
         class: AppBundle\Form\RegistrationFormType
         tags:
             - { name: "form.type", alias: "app_user_registration" }

     app.form.invitation:
         class: AppBundle\Form\InvitationFormType
         arguments: ['@app.form.data_transformer.invitation']
         tags:
             - { name: "form.type", alias: "app_invitation_type" }

     app.form.data_transformer.invitation:
         class: AppBundle\Form\DataTransformer\InvitationToCodeTransformer
         arguments: ['@doctrine.orm.entity_manager']
         public: false

     app.form.profile:
         class: AppBundle\Form\ProfileFormType
         tags:
            - { name: "form.type", alias: "app_user_profile" }

     app.form.group:
              class: AppBundle\Form\GroupFormType
              tags:
                 - { name: "form.type", alias: "app_admin_add_group" }
